<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="44" started-at="2020-06-07T09:19:05Z" finished-at="2020-06-07T09:19:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="44" started-at="2020-06-07T09:19:05Z" finished-at="2020-06-07T09:19:05Z">
      <class name="Academy.validateTitle">
        <test-method status="FAIL" signature="initialize()[pri:0, instance:Academy.validateTitle@446293d]" name="initialize" is-config="true" duration-ms="0" started-at="2020-06-07T14:49:05Z" finished-at="2020-06-07T14:49:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at resources.base.initializeDriver(base.java:37)
	at Academy.validateTitle.initialize(validateTitle.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="SKIP" signature="validateAppTitle()[pri:0, instance:Academy.validateTitle@446293d]" name="validateAppTitle" duration-ms="2" started-at="2020-06-07T14:49:05Z" finished-at="2020-06-07T14:49:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAppTitle -->
        <test-method status="SKIP" signature="validateHeader()[pri:0, instance:Academy.validateTitle@446293d]" name="validateHeader" duration-ms="2" started-at="2020-06-07T14:49:05Z" finished-at="2020-06-07T14:49:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeader -->
        <test-method status="SKIP" signature="teardown()[pri:0, instance:Academy.validateTitle@446293d]" name="teardown" is-config="true" duration-ms="0" started-at="2020-06-07T14:49:05Z" finished-at="2020-06-07T14:49:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Academy.validateTitle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
